"""add daily_summary_deliveries

Revision ID: 174091ecfa5e
Revises: bbaf3d863773
Create Date: 2026-01-18 14:24:02.364449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174091ecfa5e'
down_revision: Union[str, Sequence[str], None] = 'bbaf3d863773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summary_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_ai', sa.Boolean(), nullable=True),
    sa.Column('ai_error', sa.String(length=100), nullable=True),
    sa.Column('slack_response', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'summary_date', name='uq_daily_summary_kind_date')
    )
    op.create_index(op.f('ix_daily_summary_deliveries_kind'), 'daily_summary_deliveries', ['kind'], unique=False)
    op.create_index(op.f('ix_daily_summary_deliveries_status'), 'daily_summary_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_daily_summary_deliveries_summary_date'), 'daily_summary_deliveries', ['summary_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_summary_deliveries_summary_date'), table_name='daily_summary_deliveries')
    op.drop_index(op.f('ix_daily_summary_deliveries_status'), table_name='daily_summary_deliveries')
    op.drop_index(op.f('ix_daily_summary_deliveries_kind'), table_name='daily_summary_deliveries')
    op.drop_table('daily_summary_deliveries')
    # ### end Alembic commands ###
