"""extend events for webhook observability

Revision ID: 46ee09cd231d
Revises: 9367c62be002
Create Date: 2026-01-08 15:51:28.775981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ee09cd231d'
down_revision: Union[str, Sequence[str], None] = '9367c62be002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.String(length=20), nullable=False, server_default='verified'))
    op.add_column('events', sa.Column('signature', sa.String(), nullable=True))
    op.add_column('events', sa.Column('livemode', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('created_at_provider', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('events', 'provider_event_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('events', 'status', server_default=None)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('events', 'provider_event_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('events', 'created_at_provider')
    op.drop_column('events', 'livemode')
    op.drop_column('events', 'signature')
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
