"""add provider_event_id to events

Revision ID: 8fd4c79dae8b
Revises: ab65a21103f2
Create Date: 2026-01-07 14:50:57.504358

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fd4c79dae8b'
down_revision: Union[str, Sequence[str], None] = 'ab65a21103f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('provider_event_id', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_events_provider_event_id'), 'events', ['provider_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_provider_event_id'), table_name='events')
    op.drop_column('events', 'provider_event_id')
    # ### end Alembic commands ###
