"""change events.raw to jsonb

Revision ID: 9367c62be002
Revises: 8fd4c79dae8b
Create Date: 2026-01-07 20:53:36.354414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9367c62be002'
down_revision: Union[str, Sequence[str], None] = '8fd4c79dae8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE events ALTER COLUMN raw TYPE jsonb USING raw::jsonb;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE events ALTER COLUMN raw TYPE varchar USING raw::text;")
    # ### end Alembic commands ###
