"""add anomaly status timestamps

Revision ID: fb505ab209c9
Revises: 7d108f3e7baa
Create Date: 2026-01-13 17:10:25.759957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb505ab209c9'
down_revision: Union[str, Sequence[str], None] = '7d108f3e7baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_summary_deliveries_kind'), table_name='daily_summary_deliveries')
    op.drop_index(op.f('ix_daily_summary_deliveries_status'), table_name='daily_summary_deliveries')
    op.drop_index(op.f('ix_daily_summary_deliveries_summary_date'), table_name='daily_summary_deliveries')
    op.drop_table('daily_summary_deliveries')
    op.add_column('anomalies', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('anomalies', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('anomalies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomalies', 'updated_at')
    op.drop_column('anomalies', 'resolved_at')
    op.drop_column('anomalies', 'acknowledged_at')
    op.create_table('daily_summary_deliveries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('summary_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used_ai', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ai_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('slack_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_summary_deliveries_pkey')),
    sa.UniqueConstraint('kind', 'summary_date', name=op.f('uq_daily_summary_kind_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_daily_summary_deliveries_summary_date'), 'daily_summary_deliveries', ['summary_date'], unique=False)
    op.create_index(op.f('ix_daily_summary_deliveries_status'), 'daily_summary_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_daily_summary_deliveries_kind'), 'daily_summary_deliveries', ['kind'], unique=False)
    # ### end Alembic commands ###
